devices:
  - name: r1
    vendor: cisco
    device_type: cisco_ios
    host: 192.168.1.1
    # username and password removed and secured in GitHub Secrets

  - name: r2
    vendor: juniper
    device_type: juniper_junos
    host: 192.168.1.2
    # username and password removed and secured in GitHub Secrets